[workspace]
resolver = "2"
members = [
    "error",
    "archive",
    "auth",
    "core",
    "download_manager",
    "filesystem",
    "gzip",
    "hashing",
    "http_client",
    "instance_manager",
    "json",
    "launcher_api",
    "markdown",
    "memory_profiler",
    "mod_metadata",
    "process_launcher",
    "settings",
    "string_utils",
]
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
