name: E2E FTB

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-ftb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: "recursive"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run FTB tests
        run: cargo test test_ftb
        working-directory: crates
