name: E2E Modrinth
on: [push, pull_request]
jobs:
  test-modrinth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test test_modrinth --manifest-path crates/core/Cargo.toml
