name: E2E ATLauncher
on: [push, pull_request]
jobs:
  test-atlauncher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test test_atl --manifest-path crates/core/Cargo.toml
